# Generated by Django 2.0.4 on 2018-06-22 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('age', models.IntegerField(blank=True, max_length=5, null=True)),
                ('address', models.TextField()),
            ],
        ),
    ]
